use std::sync::OnceLock;

use types::{BoidWeightsDef, HullClass, ProjectileSubtype, Role, ShipDef, WeaponDef};

// ── Hull tonnage ──────────────────────────────────────────────────────────────

pub fn tonnage(hull_class: HullClass) -> i32 {
    match hull_class {
        HullClass::Corvette => 2,
        HullClass::Frigate => 4,
        HullClass::Destroyer => 6,
        HullClass::Cruiser => 10,
        HullClass::Battlecruiser => 16,
        HullClass::Dreadnought => 24,
    }
}

// ── Weapon helpers ────────────────────────────────────────────────────────────

pub fn hitscan(damage: f64, range: f64, cooldown_ticks: u32) -> WeaponDef {
    WeaponDef::Hitscan {
        damage,
        range,
        cooldown_ticks,
        miss_chance: 0.0,
        crit_chance: 0.0,
        crit_damage: 1.0,
        ammo: None,
    }
}

pub fn missile(
    damage: f64,
    range: f64,
    speed: f64,
    turn_rate: f64,
    cooldown_ticks: u32,
) -> WeaponDef {
    WeaponDef::Projectile {
        subtype: Some(ProjectileSubtype::SeekingMissile),
        damage,
        range,
        cooldown_ticks,
        projectile_speed: speed,
        turn_rate,
        fuse_ticks: (range / speed * 1.5) as u32 + 30,
        explosion_radius: 0.0,
        explosion_damage: 0.0,
        crit_chance: 0.0,
        crit_damage: 1.0,
        ammo: None,
    }
}

pub fn torpedo(
    damage: f64,
    expl_damage: f64,
    range: f64,
    speed: f64,
    expl_radius: f64,
    cooldown_ticks: u32,
) -> WeaponDef {
    WeaponDef::Projectile {
        subtype: Some(ProjectileSubtype::Torpedo),
        damage,
        range,
        cooldown_ticks,
        projectile_speed: speed,
        turn_rate: 0.0,
        fuse_ticks: (range / speed * 1.5) as u32 + 30,
        explosion_radius: expl_radius,
        explosion_damage: expl_damage,
        crit_chance: 0.0,
        crit_damage: 1.0,
        ammo: None,
    }
}

pub fn mine_layer(expl_damage: f64, expl_radius: f64, cooldown_ticks: u32) -> WeaponDef {
    WeaponDef::Projectile {
        subtype: Some(ProjectileSubtype::Mine),
        damage: 0.0,
        range: expl_radius * 2.0,
        cooldown_ticks,
        projectile_speed: 0.3,
        turn_rate: 0.0,
        fuse_ticks: 480, // 16s at 30Hz before self-destructing
        explosion_radius: expl_radius,
        explosion_damage: expl_damage,
        crit_chance: 0.0,
        crit_damage: 1.0,
        ammo: None,
    }
}

pub fn beam(
    damage: f64,
    range: f64,
    beam_width: f64,
    charge_ticks: u32,
    duration_ticks: u32,
    slew_rate: f64,
    track_rate: f64,
    ramp_ticks: u32,
    ramp_max: f64,
    cooldown_ticks: u32,
) -> WeaponDef {
    WeaponDef::Beam {
        damage,
        range,
        cooldown_ticks,
        charge_ticks,
        duration_ticks,
        beam_width,
        slew_rate,
        track_rate,
        ramp_ticks,
        ramp_max,
        crit_chance: 0.0,
        crit_damage: 1.0,
        ammo: None,
    }
}

// ── Blueprint catalog ─────────────────────────────────────────────────────────

pub struct Blueprint {
    pub id: &'static str,
    pub display_name: &'static str,
    pub salvage_cost: i32,
    pub hull_class: HullClass,
    pub ship_def: ShipDef,
}

impl Blueprint {
    pub fn tonnage(&self) -> i32 {
        tonnage(self.hull_class)
    }
}

static BLUEPRINTS: OnceLock<Vec<Blueprint>> = OnceLock::new();

pub fn blueprints() -> &'static [Blueprint] {
    BLUEPRINTS.get_or_init(build_blueprints).as_slice()
}

pub fn find_blueprint(id: &str) -> Option<&'static Blueprint> {
    blueprints().iter().find(|bp| bp.id == id)
}

fn build_blueprints() -> Vec<Blueprint> {
    vec![
        // ── Corvettes (2T) ────────────────────────────────────────────────────
        Blueprint {
            id: "torpedo_corvette",
            display_name: "Torpedo Corvette",
            salvage_cost: 18,
            hull_class: HullClass::Corvette,
            ship_def: ShipDef {
                blueprint_drawing_id: "corvette_a".into(),
                hull_class: HullClass::Corvette,
                role: Role::Torpedo,
                weight: None,
                hp: 55.0,
                max_hp: 55.0,
                speed: 7.0,
                acceleration: 2.0,
                turn_rate: 1.0,
                boid_weights: BoidWeightsDef {
                    separation: 1.5,
                    cohesion: 0.2,
                    alignment: 0.2,
                    seek_enemy: 0.6,
                    maintain_range: 2.5,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(torpedo(20.0, 40.0, 150.0, 5.5, 25.0, 60)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "fighter_corvette",
            display_name: "Fighter Corvette",
            salvage_cost: 10,
            hull_class: HullClass::Corvette,
            ship_def: ShipDef {
                blueprint_drawing_id: "corvette_a".into(),
                hull_class: HullClass::Corvette,
                role: Role::Fighter,
                weight: None,
                hp: 60.0,
                max_hp: 60.0,
                speed: 8.0,
                acceleration: 2.0,
                turn_rate: 1.2,
                boid_weights: BoidWeightsDef {
                    separation: 1.5,
                    cohesion: 0.4,
                    alignment: 0.3,
                    seek_enemy: 2.0,
                    maintain_range: 1.0,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(hitscan(10.0, 80.0, 15)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "missile_corvette",
            display_name: "Missile Corvette",
            salvage_cost: 15,
            hull_class: HullClass::Corvette,
            ship_def: ShipDef {
                blueprint_drawing_id: "corvette_a".into(),
                hull_class: HullClass::Corvette,
                role: Role::Missile,
                weight: None,
                hp: 50.0,
                max_hp: 50.0,
                speed: 9.0,
                acceleration: 2.5,
                turn_rate: 1.5,
                boid_weights: BoidWeightsDef {
                    separation: 2.0,
                    cohesion: 0.3,
                    alignment: 0.2,
                    seek_enemy: 1.8,
                    maintain_range: 1.5,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(missile(35.0, 200.0, 18.0, 0.08, 50)),
                equipment: vec![],
            },
        },
        // ── Frigates (4T) ─────────────────────────────────────────────────────
        Blueprint {
            id: "torpedo_frigate",
            display_name: "Torpedo Frigate",
            salvage_cost: 40,
            hull_class: HullClass::Frigate,
            ship_def: ShipDef {
                blueprint_drawing_id: "frigate_a".into(),
                hull_class: HullClass::Frigate,
                role: Role::Torpedo,
                weight: None,
                hp: 130.0,
                max_hp: 130.0,
                speed: 3.5,
                acceleration: 0.9,
                turn_rate: 0.5,
                boid_weights: BoidWeightsDef {
                    separation: 1.2,
                    cohesion: 0.2,
                    alignment: 0.2,
                    seek_enemy: 0.5,
                    maintain_range: 2.5,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(torpedo(30.0, 60.0, 180.0, 5.0, 30.0, 75)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "fighter_frigate",
            display_name: "Fighter Frigate",
            salvage_cost: 25,
            hull_class: HullClass::Frigate,
            ship_def: ShipDef {
                blueprint_drawing_id: "frigate_a".into(),
                hull_class: HullClass::Frigate,
                role: Role::Fighter,
                weight: None,
                hp: 130.0,
                max_hp: 130.0,
                speed: 5.0,
                acceleration: 1.2,
                turn_rate: 0.8,
                boid_weights: BoidWeightsDef {
                    separation: 1.2,
                    cohesion: 0.5,
                    alignment: 0.4,
                    seek_enemy: 1.5,
                    maintain_range: 1.2,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(hitscan(20.0, 100.0, 20)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "point_defense_frigate",
            display_name: "Point Defense Frigate",
            salvage_cost: 30,
            hull_class: HullClass::Frigate,
            ship_def: ShipDef {
                blueprint_drawing_id: "frigate_a".into(),
                hull_class: HullClass::Frigate,
                role: Role::PointDefense,
                weight: None,
                hp: 110.0,
                max_hp: 110.0,
                speed: 4.5,
                acceleration: 1.0,
                turn_rate: 0.7,
                boid_weights: BoidWeightsDef {
                    separation: 1.8,
                    cohesion: 0.6,
                    alignment: 0.5,
                    seek_enemy: 1.0,
                    maintain_range: 2.0,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(hitscan(6.0, 65.0, 8)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "missile_frigate",
            display_name: "Missile Frigate",
            salvage_cost: 35,
            hull_class: HullClass::Frigate,
            ship_def: ShipDef {
                blueprint_drawing_id: "frigate_a".into(),
                hull_class: HullClass::Frigate,
                role: Role::Missile,
                weight: None,
                hp: 120.0,
                max_hp: 120.0,
                speed: 4.0,
                acceleration: 1.0,
                turn_rate: 0.6,
                boid_weights: BoidWeightsDef {
                    separation: 1.3,
                    cohesion: 0.4,
                    alignment: 0.3,
                    seek_enemy: 1.2,
                    maintain_range: 2.0,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(missile(50.0, 220.0, 8.0, 0.06, 60)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "mine_frigate",
            display_name: "Mine Layer Frigate",
            salvage_cost: 40,
            hull_class: HullClass::Frigate,
            ship_def: ShipDef {
                blueprint_drawing_id: "frigate_a".into(),
                hull_class: HullClass::Frigate,
                role: Role::Mine,
                weight: None,
                hp: 140.0,
                max_hp: 140.0,
                speed: 3.5,
                acceleration: 0.9,
                turn_rate: 0.5,
                boid_weights: BoidWeightsDef {
                    separation: 1.5,
                    cohesion: 0.3,
                    alignment: 0.2,
                    seek_enemy: 0.6,
                    maintain_range: 2.5,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(mine_layer(80.0, 45.0, 80)),
                equipment: vec![],
            },
        },
        // ── Destroyers (6T) ──────────────────────────────────────────────────
        Blueprint {
            id: "artillery_destroyer",
            display_name: "Artillery Destroyer",
            salvage_cost: 45,
            hull_class: HullClass::Destroyer,
            ship_def: ShipDef {
                blueprint_drawing_id: "destroyer_a".into(),
                hull_class: HullClass::Destroyer,
                role: Role::Artillery,
                weight: None,
                hp: 200.0,
                max_hp: 200.0,
                speed: 3.0,
                acceleration: 0.8,
                turn_rate: 0.5,
                boid_weights: BoidWeightsDef {
                    separation: 1.0,
                    cohesion: 0.3,
                    alignment: 0.3,
                    seek_enemy: 0.8,
                    maintain_range: 1.5,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(hitscan(40.0, 150.0, 45)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "torpedo_destroyer",
            display_name: "Torpedo Destroyer",
            salvage_cost: 55,
            hull_class: HullClass::Destroyer,
            ship_def: ShipDef {
                blueprint_drawing_id: "destroyer_a".into(),
                hull_class: HullClass::Destroyer,
                role: Role::Torpedo,
                weight: None,
                hp: 250.0,
                max_hp: 250.0,
                speed: 2.5,
                acceleration: 0.6,
                turn_rate: 0.4,
                boid_weights: BoidWeightsDef {
                    separation: 1.0,
                    cohesion: 0.2,
                    alignment: 0.2,
                    seek_enemy: 0.6,
                    maintain_range: 2.5,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(torpedo(40.0, 80.0, 220.0, 5.0, 35.0, 90)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "beam_destroyer",
            display_name: "Beam Destroyer",
            salvage_cost: 65,
            hull_class: HullClass::Destroyer,
            ship_def: ShipDef {
                blueprint_drawing_id: "destroyer_a".into(),
                hull_class: HullClass::Destroyer,
                role: Role::Artillery,
                weight: None,
                hp: 180.0,
                max_hp: 180.0,
                speed: 2.5,
                acceleration: 0.6,
                turn_rate: 0.4,
                boid_weights: BoidWeightsDef {
                    separation: 1.0,
                    cohesion: 0.3,
                    alignment: 0.3,
                    seek_enemy: 0.8,
                    maintain_range: 2.0,
                },
                armor: 0.0,
                shield_hp: 60.0,
                shield_max_hp: 60.0,
                shield_recharge_rate: 1.0,
                // 8 dmg/tick, 45 ticks firing = 360 total + ramp to 2× = ~540 effective
                weapon: Some(beam(8.0, 220.0, 5.0, 30, 45, 0.12, 0.02, 20, 2.0, 90)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "railgun_destroyer",
            display_name: "Railgun Destroyer",
            salvage_cost: 60,
            hull_class: HullClass::Destroyer,
            ship_def: ShipDef {
                blueprint_drawing_id: "destroyer_a".into(),
                hull_class: HullClass::Destroyer,
                role: Role::Railgun,
                weight: None,
                hp: 150.0,
                max_hp: 150.0,
                speed: 2.0,
                acceleration: 0.5,
                turn_rate: 0.3,
                boid_weights: BoidWeightsDef {
                    separation: 1.2,
                    cohesion: 0.2,
                    alignment: 0.2,
                    seek_enemy: 0.5,
                    maintain_range: 3.0,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(hitscan(65.0, 260.0, 60)),
                equipment: vec![],
            },
        },
        // ── Cruisers (10T) ───────────────────────────────────────────────────
        Blueprint {
            id: "torpedo_cruiser",
            display_name: "Torpedo Cruiser",
            salvage_cost: 100,
            hull_class: HullClass::Cruiser,
            ship_def: ShipDef {
                blueprint_drawing_id: "cruiser_a".into(),
                hull_class: HullClass::Cruiser,
                role: Role::Torpedo,
                weight: None,
                hp: 300.0,
                max_hp: 300.0,
                speed: 2.5,
                acceleration: 0.6,
                turn_rate: 0.4,
                boid_weights: BoidWeightsDef {
                    separation: 1.0,
                    cohesion: 0.2,
                    alignment: 0.2,
                    seek_enemy: 0.5,
                    maintain_range: 2.5,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(torpedo(60.0, 120.0, 250.0, 5.5, 45.0, 100)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "fighter_cruiser",
            display_name: "Fighter Cruiser",
            salvage_cost: 85,
            hull_class: HullClass::Cruiser,
            ship_def: ShipDef {
                blueprint_drawing_id: "cruiser_a".into(),
                hull_class: HullClass::Cruiser,
                role: Role::Fighter,
                weight: None,
                hp: 350.0,
                max_hp: 350.0,
                speed: 5.0,
                acceleration: 1.0,
                turn_rate: 0.7,
                boid_weights: BoidWeightsDef {
                    separation: 1.0,
                    cohesion: 0.6,
                    alignment: 0.4,
                    seek_enemy: 1.8,
                    maintain_range: 1.0,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(hitscan(28.0, 95.0, 18)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "artillery_cruiser",
            display_name: "Artillery Cruiser",
            salvage_cost: 95,
            hull_class: HullClass::Cruiser,
            ship_def: ShipDef {
                blueprint_drawing_id: "cruiser_a".into(),
                hull_class: HullClass::Cruiser,
                role: Role::Artillery,
                weight: None,
                hp: 280.0,
                max_hp: 280.0,
                speed: 2.5,
                acceleration: 0.6,
                turn_rate: 0.4,
                boid_weights: BoidWeightsDef {
                    separation: 1.0,
                    cohesion: 0.3,
                    alignment: 0.3,
                    seek_enemy: 0.7,
                    maintain_range: 2.0,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(hitscan(70.0, 210.0, 55)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "beam_cruiser",
            display_name: "Beam Cruiser",
            salvage_cost: 100,
            hull_class: HullClass::Cruiser,
            ship_def: ShipDef {
                blueprint_drawing_id: "cruiser_a".into(),
                hull_class: HullClass::Cruiser,
                role: Role::Artillery,
                weight: None,
                hp: 320.0,
                max_hp: 320.0,
                speed: 2.5,
                acceleration: 0.6,
                turn_rate: 0.35,
                boid_weights: BoidWeightsDef {
                    separation: 1.0,
                    cohesion: 0.3,
                    alignment: 0.3,
                    seek_enemy: 0.7,
                    maintain_range: 2.0,
                },
                armor: 0.05,
                shield_hp: 80.0,
                shield_max_hp: 80.0,
                shield_recharge_rate: 1.5,
                weapon: Some(beam(12.0, 260.0, 7.0, 40, 60, 0.10, 0.02, 25, 2.5, 120)),
                equipment: vec![],
            },
        },
        // ── Battlecruisers (16T) ─────────────────────────────────────────────
        Blueprint {
            id: "torpedo_battlecruiser",
            display_name: "Torpedo Battlecruiser",
            salvage_cost: 175,
            hull_class: HullClass::Battlecruiser,
            ship_def: ShipDef {
                blueprint_drawing_id: "battlecruiser_a".into(),
                hull_class: HullClass::Battlecruiser,
                role: Role::Torpedo,
                weight: None,
                hp: 500.0,
                max_hp: 500.0,
                speed: 2.0,
                acceleration: 0.5,
                turn_rate: 0.3,
                boid_weights: BoidWeightsDef {
                    separation: 1.0,
                    cohesion: 0.2,
                    alignment: 0.2,
                    seek_enemy: 0.4,
                    maintain_range: 3.0,
                },
                armor: 0.1,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(torpedo(100.0, 200.0, 280.0, 6.0, 60.0, 120)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "assault_battlecruiser",
            display_name: "Assault Battlecruiser",
            salvage_cost: 160,
            hull_class: HullClass::Battlecruiser,
            ship_def: ShipDef {
                blueprint_drawing_id: "battlecruiser_a".into(),
                hull_class: HullClass::Battlecruiser,
                role: Role::Fighter,
                weight: None,
                hp: 600.0,
                max_hp: 600.0,
                speed: 3.5,
                acceleration: 0.7,
                turn_rate: 0.4,
                boid_weights: BoidWeightsDef {
                    separation: 0.8,
                    cohesion: 0.5,
                    alignment: 0.4,
                    seek_enemy: 1.5,
                    maintain_range: 1.0,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(hitscan(55.0, 120.0, 30)),
                equipment: vec![],
            },
        },
        Blueprint {
            id: "siege_battlecruiser",
            display_name: "Siege Battlecruiser",
            salvage_cost: 180,
            hull_class: HullClass::Battlecruiser,
            ship_def: ShipDef {
                blueprint_drawing_id: "battlecruiser_a".into(),
                hull_class: HullClass::Battlecruiser,
                role: Role::Artillery,
                weight: None,
                hp: 450.0,
                max_hp: 450.0,
                speed: 2.0,
                acceleration: 0.5,
                turn_rate: 0.3,
                boid_weights: BoidWeightsDef {
                    separation: 1.0,
                    cohesion: 0.2,
                    alignment: 0.2,
                    seek_enemy: 0.5,
                    maintain_range: 2.5,
                },
                armor: 0.0,
                shield_hp: 0.0,
                shield_max_hp: 0.0,
                shield_recharge_rate: 0.0,
                weapon: Some(hitscan(120.0, 250.0, 75)),
                equipment: vec![],
            },
        },
    ]
}

// ── Mothership templates ──────────────────────────────────────────────────────

// Returns the canonical mothership ShipDef for a given faction.
// Panics if the faction_id is not recognised — this is a catalog authoring error.
pub fn mothership_template(faction_id: &str) -> ShipDef {
    match faction_id {
        // Legacy faction id used in hand-authored fleet JSON files.
        "player" | "gallforce" => ShipDef {
            blueprint_drawing_id: "mothership_a".into(),
            hull_class: HullClass::Dreadnought,
            role: Role::Artillery,
            weight: None,
            hp: 500.0,
            max_hp: 500.0,
            speed: 1.0,
            acceleration: 0.3,
            turn_rate: 0.1,
            boid_weights: BoidWeightsDef {
                separation: 2.0,
                cohesion: 0.0,
                alignment: 0.0,
                seek_enemy: 0.2,
                maintain_range: 1.0,
            },
            armor: 0.0,
            shield_hp: 0.0,
            shield_max_hp: 0.0,
            shield_recharge_rate: 0.0,
            weapon: Some(hitscan(25.0, 200.0, 45)),
            equipment: vec![],
        },
        "iron_legion" => ShipDef {
            blueprint_drawing_id: "mothership_a".into(),
            hull_class: HullClass::Dreadnought,
            role: Role::Artillery,
            weight: None,
            hp: 600.0,
            max_hp: 600.0,
            speed: 0.8,
            acceleration: 0.2,
            turn_rate: 0.08,
            boid_weights: BoidWeightsDef {
                separation: 2.0,
                cohesion: 0.0,
                alignment: 0.0,
                seek_enemy: 0.2,
                maintain_range: 1.0,
            },
            armor: 0.10,
            shield_hp: 0.0,
            shield_max_hp: 0.0,
            shield_recharge_rate: 0.0,
            weapon: Some(hitscan(35.0, 230.0, 50)),
            equipment: vec![],
        },
        "freetraders" => ShipDef {
            blueprint_drawing_id: "mothership_a".into(),
            hull_class: HullClass::Dreadnought,
            role: Role::Artillery,
            weight: None,
            hp: 450.0,
            max_hp: 450.0,
            speed: 1.2,
            acceleration: 0.4,
            turn_rate: 0.12,
            boid_weights: BoidWeightsDef {
                separation: 2.0,
                cohesion: 0.0,
                alignment: 0.0,
                seek_enemy: 0.2,
                maintain_range: 1.0,
            },
            armor: 0.0,
            shield_hp: 80.0,
            shield_max_hp: 80.0,
            shield_recharge_rate: 2.0,
            weapon: Some(hitscan(20.0, 180.0, 40)),
            equipment: vec![],
        },
        _ => panic!("unknown faction_id '{faction_id}' — add a mothership_template entry"),
    }
}
