@startuml
!include .\\client\src\meta\AdmiralCatalog.puml
!include .\\client\src\meta\AdmiralEffectsRegistry.puml
!include .\\client\src\meta\AdmiralSelectUi.puml
!include .\\client\src\meta\AdmiralSession.puml
!include .\\client\src\meta\BattleInputs.puml
!include .\\client\src\meta\BattleOutcomeResolver.puml
!include .\\client\src\meta\DockSession.puml
!include .\\client\src\meta\DockUi.puml
!include .\\client\src\meta\Faction.puml
!include .\\client\src\meta\FleetData.puml
!include .\\client\src\meta\IAdmiralStore.puml
!include .\\client\src\meta\IDockyard.puml
!include .\\client\src\meta\IRunData.puml
!include .\\client\src\meta\IRunStore.puml
!include .\\client\src\meta\IStatsStore.puml
!include .\\client\src\meta\JumpRecord.puml
!include .\\client\src\meta\LifetimeStats.puml
!include .\\client\src\meta\LocalAdmiralAdapter.puml
!include .\\client\src\meta\LocalAdmiralStore.puml
!include .\\client\src\meta\LocalDockyardAdapter.puml
!include .\\client\src\meta\LocalRunStore.puml
!include .\\client\src\meta\LocalStatsStore.puml
!include .\\client\src\meta\MainMenuUi.puml
!include .\\client\src\meta\OptionsOverlay.puml
!include .\\client\src\meta\ResearchUpgrade.puml
!include .\\client\src\meta\RunEndUi.puml
!include .\\client\src\meta\RunSnapshot.puml
!include .\\client\src\meta\RunState.puml
!include .\\client\src\meta\UserSettings.puml
!include .\\client\src\rendering\BattleRenderer.puml
!include .\\client\src\rendering\BeamNode.puml
!include .\\client\src\rendering\ExplosionEffect.puml
!include .\\client\src\rendering\HitscanEffect.puml
!include .\\client\src\rendering\ProjectileNode.puml
!include .\\client\src\rendering\ShipNode.puml
!include .\\client\src\sim\BattleLog.puml
!include .\\client\src\sim\BattleLogParser.puml
!include .\\client\src\sim\ISimRunner.puml
!include .\\client\src\sim\LocalSimRunner.puml
!include .\\client\src\sim\PlaybackState.puml
!include .\\client\src\sim\SimRunner.puml
!include .\\client\src\sim\StoredLogSimRunner.puml
!include .\\client\src\ui\DebugOverlay.puml
!include .\\client\src\ui\FleetInspector.puml
@enduml
