@startuml
class Admiral <<sealed>> {
    + <<required>> Id : string <<get>> <<init>>
    + <<required>> Name : string <<get>> <<init>>
    + <<required>> FactionId : string <<get>> <<init>>
    + <<required>> BonusText : string <<get>> <<init>>
    + <<required>> StartingSalvage : int <<get>> <<init>>
    + <<required>> StartingTech : int <<get>> <<init>>
    + <<required>> StartingHangarCapacity : int <<get>> <<init>>
    + <<required>> StartingFleet : FleetJsonData <<get>> <<init>>
}
@enduml
