@startuml
class DockUi <<partial>> {
    + <<override>> _Ready() : void
    + <<override>> _ExitTree() : void
}
class SessionShip <<sealed>> <<record>> {
    + CurrentIndex : int <<get>> <<init>>
    + Name : string <<get>> <<init>>
    + Tonnage : int <<get>> <<init>>
}
Control <|-- DockUi
DockUi +-- SessionShip
@enduml
