@startuml
class LifetimeStats <<sealed>> {
    + TotalRunVictories : int <<get>> <<set>>
    + TotalBattlesWon : int <<get>> <<set>>
    + TotalEnemyShipsDestroyed : int <<get>> <<set>>
    + TotalSalvageSpent : int <<get>> <<set>>
    + TotalTechSpent : int <<get>> <<set>>
    + TotalCapitalShipsBought : int <<get>> <<set>>
}
@enduml
