@startuml
class MainMenuUi <<partial>> {
    - _newRunConfirm : ConfirmationDialog
    + <<override>> _Ready() : void
    - OnStartPressed() : void
    - <<async>> StartNewRun() : void
}
Control <|-- MainMenuUi
@enduml
