@startuml
class BeamNode <<partial>> {
    - {static} <<readonly>> FleetAColor : Color
    - {static} <<readonly>> FleetBColor : Color
    - _line : Line2D
    - _baseColor : Color
    + BeamId : uint <<get>>
    + <<override>> _Ready() : void
    + Init(id:uint, fleet:byte) : void
    + ApplySnapshot(snap:BeamSnapshot, simScale:float) : void
}
Node2D <|-- BeamNode
@enduml
